---
title: "cph_738_h3"
author: "grienne"
date: "September 18, 2018"
output: pdf_document
---

```{r Foundation}

library(tidyverse)
library(maps)
library(plyr)

dat <- read.csv(file.choose(), header = TRUE)

```



```{r Question 1}

##Code Bupropion 0 is No, x>0 is Yes
dat$Bupdat <- as.factor(with(dat,ifelse(Bupropion == 0, 'No', 'Yes')))

##Check to make sure still have same number of observations
summary(dat$Bupdat)                 

##Plotting
q1 <- ggplot(data = dat, mapping = aes(y = AGE , x = Bupdat))
q1 + geom_boxplot()
q1 + geom_violin()

```



```{Question 2}

#It does not seem appropriate to compare the average age of subjects between those who use and don't use Bupriopion.
#There were over 90k "no" and only 1400 "yes." Reviewing the boxplot and the violin plot shows similar averages, however the variation in the no is heavily biased with the large number of outliers in the upper end, pulling the average higher than it might be if they were excluded. 

```


```{r Question 3}

#Create Age Categories
dat$q3_age <- with( dat,
                      ifelse( 12 <= AGE & AGE <= 18, "Adolescent", 
                        ifelse( 19<= AGE & AGE <= 27, "Young_Adult",
                          ifelse(28 <= AGE & AGE <= 65, "Adult", "Remove")      
                                )      
                              )
                            )



#Create Data Set with just those in the respective Age Categories

dat$SUD_Type <- with(dat,
                      ifelse(StUD_Type == 1, "Cocaine", "All"
                                                          )
                      )

####
q3_dat <- dat %>%
  select(StUD_Year, StUD_Type, q3_age, SUD_Type) %>%
  filter(q3_age != "Remove")


## Adolescent

q3_adol <- dat %>%
  select(q3_age,  SUD_Type, StUD_Year) %>%
  filter(q3_age == "Adolescent")

###generate percentages
q3_adol_1 <- q3_adol %>%
    group_by(q3_age, StUD_Year, SUD_Type)  %>%
      summarise(n = n()) %>%
      mutate(pct = n / sum(n))



##Young Adult  
  
q3_yadul <- dat %>%
  select(q3_age,StUD_Year, SUD_Type) %>%
  filter(q3_age == "Young_Adult")

##Age Tables Adolescent
q3_yadul <- dat %>%
  select(q3_age,  SUD_Type, StUD_Year) %>%
  filter(q3_age == "Young_Adult")

###generate percentages
q3_yadul_1 <- q3_yadul %>%
    group_by(q3_age, StUD_Year, SUD_Type)  %>%
      summarise(n = n()) %>%
      mutate(pct = n / sum(n))


##Adult
q3_adul <- dat %>%
  select(q3_age, StUD_Year, SUD_Type) %>%
  filter(q3_age == "Adult")
##Age Tables Adolescent
q3_adul <- dat %>%
  select(q3_age,  SUD_Type, StUD_Year) %>%
  filter(q3_age == "Adult")

###generate percentages
q3_adul_1 <- q3_adul %>%
    group_by(q3_age, StUD_Year, SUD_Type)  %>%
      summarise(n = n()) %>%
      mutate(pct = n / sum(n))


##write.csv(q3_dat_try, "q3_dat_try.csv")
##how to generate csv files from internally created dataframes


###

q3_final <- bind_rows(q3_adol_1, q3_adul_1, q3_yadul_1) %>%
          filter(SUD_Type != "All")


###

p_q3 <- ggplot(data = q3_final, mapping = aes(x = StUD_Year, y= pct, colour = q3_age))
p_q3 + geom_point() +  geom_line()



```


```{Question 4}
```


```{r Question 5}
us_state_map <- map_data('state') 
str(us_state_map)
summary(as.factor(map_data('state')$region))

## create a tmp data.frame with AGE and state information only
## Had NAs, removed them

q5_dat <- dat %>%
  filter(AGE <= 65) %>%
  filter(AGE >= 28)

#generate counts
#
q5_dat_1 <- q5_dat %>%
  select(EGEOLOC, SUD_Type) %>%  
    group_by(EGEOLOC, SUD_Type)  %>%
      summarise(n = n()) %>%
        set_names("EGEOLOC", "drug", "n")

q5_dat_1$region <- with(q5_dat_1,
                  ifelse(EGEOLOC == 41, 'alabama',
                  ifelse(EGEOLOC == 52, 'arizona',
                  ifelse(EGEOLOC == 46, 'arkansas',
                  ifelse(EGEOLOC == 62, 'california',
                  ifelse(EGEOLOC == 53, 'colorado',
                  ifelse(EGEOLOC == 4,  'connecticut',
                  ifelse(EGEOLOC == 32, 'delaware',
                  ifelse(EGEOLOC == 31, 'district of columbia',
                  ifelse(EGEOLOC == 33, 'florida',
                  ifelse(EGEOLOC == 34, 'georgia',
                  ifelse(EGEOLOC == 54, 'idaho',
                  ifelse(EGEOLOC == 16, 'illinois',
                  ifelse(EGEOLOC == 17, 'indiana',
                  ifelse(EGEOLOC == 22, 'iowa',
                  ifelse(EGEOLOC == 23, 'kansas',
                  ifelse(EGEOLOC == 42, 'kentucky',
                  ifelse(EGEOLOC == 47, 'lousiana',
                  ifelse(EGEOLOC ==  5, 'maine',
                  ifelse(EGEOLOC == 35, 'maryland',
                  ifelse(EGEOLOC ==  6, 'massachusetts',
                  ifelse(EGEOLOC == 18, 'michigan',
                  ifelse(EGEOLOC == 24, 'minnesota',
                  ifelse(EGEOLOC == 43, 'mississippi',
                  ifelse(EGEOLOC == 25, 'missouri',
                  ifelse(EGEOLOC == 55, 'montana',
                  ifelse(EGEOLOC == 26, 'nebraska',
                  ifelse(EGEOLOC == 56, 'nevade',
                  ifelse(EGEOLOC ==  7, 'new hampshire',
                  ifelse(EGEOLOC == 11, 'new jersey',
                  ifelse(EGEOLOC == 57, 'new mexico',
                  ifelse(EGEOLOC == 12, 'new york',
                  ifelse(EGEOLOC == 36, 'north carolina',
                  ifelse(EGEOLOC == 27, 'north dakota',
                  ifelse(EGEOLOC == 19, 'ohio',
                  ifelse(EGEOLOC == 48, 'oklahoma',
                  ifelse(EGEOLOC == 64, 'oregon',
                  ifelse(EGEOLOC == 13, 'pennsylvania',
                  ifelse(EGEOLOC ==  8, 'rhode island',
                  ifelse(EGEOLOC == 37, 'south carolina',
                  ifelse(EGEOLOC == 28, 'south dakota',
                  ifelse(EGEOLOC == 44, 'tennessee',
                  ifelse(EGEOLOC == 49, 'texas',
                  ifelse(EGEOLOC == 58, 'utah',
                  ifelse(EGEOLOC ==  9, 'vermont',
                  ifelse(EGEOLOC == 38, 'virginia',
                  ifelse(EGEOLOC == 65, 'washington',
                  ifelse(EGEOLOC == 39, 'west virginia',
                  ifelse(EGEOLOC == 20, 'wisconsin',
                  ifelse(EGEOLOC == 59, 'wyoming',
                         NA))))))))))))))))))))))))))))))))))))))))))))))))))

q5_dat_1_final <- q5_dat_1 %>%
  select(region, drug, n) %>%
    mutate(prop = n / sum(n))


aggregate(n ~ region, data = q5_dat_1_final, FUN = sum) 

##success
q5_dat_final <- q5_dat_1_final %>%
      select(region, drug, prop) %>%
        filter(drug != "All")


## list of states
states = c("alabama","arizona","arkansas","california",
           "colorado","connecticut","delaware","district of columbia",
           "florida","georgia","idaho","illinois",
           "indiana","iowa","kansas","kentucky",
           "louisiana","maine","maryland","massachusetts",
           "michigan","minnesota","mississippi","missouri",
           "montana","nebraska","nevada","new hampshire",
           "new jersey","new mexico","new york","north carolina",
           "north dakota","ohio","oklahoma","oregon",
           "pennsylvania","rhode island","south carolina","south dakota",
           "tennessee","texas","utah","vermont",
           "virginia","washington","west virginia","wisconsin",
           "wyoming")



## merge with state map data
map_dat_prop <- merge(us_state_map, q5_dat_final, by ='region', all = T) 

## plot
p <- ggplot(map_dat_prop, aes(x = long, y = lat, group = group)) 
p + geom_polygon(aes(fill = prop)) + 
  geom_path(colour = 'gray') 

```


```{Question 6}

States with the highest CUD Prevalence

```






